// Shared collision and path planning. Coordinates are world-space X/Z.
export function makeNavigation({bounds, obstacles=[], extra=()=>true, floor=()=>.25}, radius=.62){
 const contains=(x,z,o,pad=radius)=>o.kind==='circle'?Math.hypot(x-o.x,z-o.z)<o.r+pad:(x>o.x0-pad&&x<o.x1+pad&&z>o.z0-pad&&z<o.z1+pad);
 const valid=(x,z)=>Number.isFinite(x)&&Number.isFinite(z)&&x>=bounds[0]+radius&&x<=bounds[1]-radius&&z>=bounds[2]+radius&&z<=bounds[3]-radius&&extra(x,z)&&!obstacles.some(o=>contains(x,z,o,radius+(o.padding||0)));
 function nearest(x,z){if(valid(x,z))return{x,z};for(let r=.3;r<=3;r+=.3)for(let i=0;i<24;i++){const a=i*Math.PI/12,xx=x+Math.cos(a)*r,zz=z+Math.sin(a)*r;if(valid(xx,zz))return{x:xx,z:zz}}return null}
 function clear(a,b){const d=Math.hypot(b.x-a.x,b.z-a.z),n=Math.max(1,Math.ceil(d/.025));for(let i=1;i<=n;i++)if(!valid(a.x+(b.x-a.x)*i/n,a.z+(b.z-a.z)*i/n))return false;return true}
 function path(start,target){const end=nearest(target.x,target.z);if(!end||!valid(start.x,start.z))return [];if(clear(start,end))return[end];const step=.42,ox=start.x,oz=start.z,goal=(x,z)=>Math.hypot(x-end.x,z-end.z);const first={i:0,j:0,x:ox,z:oz,g:0,f:goal(ox,oz),parent:null},open=[first],seen=new Map([['0,0',first]]),closed=new Set();let terminal=null;
 for(let iter=0;open.length&&iter<20000;iter++){let best=0;for(let k=1;k<open.length;k++)if(open[k].f<open[best].f)best=k;const n=open.splice(best,1)[0],key=n.i+','+n.j;if(closed.has(key))continue;closed.add(key);if(goal(n.x,n.z)<step*1.6&&clear(n,end)){terminal=n;break}for(let di=-1;di<=1;di++)for(let dj=-1;dj<=1;dj++){if(!di&&!dj)continue;const i=n.i+di,j=n.j+dj,x=ox+i*step,z=oz+j*step,k=i+','+j;if(closed.has(k)||!valid(x,z)||!clear(n,{x,z}))continue;const g=n.g+step*Math.hypot(di,dj);if(seen.has(k)&&seen.get(k).g<=g)continue;const next={i,j,x,z,g,f:g+goal(x,z),parent:n};seen.set(k,next);open.push(next)}}
 if(!terminal)return[];const raw=[end];while(terminal.parent){raw.unshift({x:terminal.x,z:terminal.z});terminal=terminal.parent}const smooth=[];let prev=start;while(raw.length){let i=raw.length-1;while(i>0&&!clear(prev,raw[i]))i--;smooth.push(raw[i]);prev=raw[i];raw.splice(0,i+1)}return smooth;
 }
 return{valid,path,clear,nearest,floor,obstacles,bounds};
}
const rect=(id,x0,x1,z0,z1,padding=0)=>({id,kind:'rect',x0,x1,z0,z1,padding});
export const houseObstacles=[rect('complete-house',-4.65,4.65,-7.7,-.35),rect('side-house',-10.6,-5.4,-4.1,.1),rect('table',-1.95,1.95,5.73,8.27),rect('left-chair',-3.48,-2.52,6.5,7.5),rect('right-chair',2.52,3.48,6.5,7.5),{kind:'circle',x:-8,z:6,r:2.5},{kind:'circle',x:9,z:2,r:.5},rect('north-stool',-.48,.48,3.72,4.68),rect('south-stool',-.48,.48,9.32,10.28),rect('vegetables',-9.65,-6.35,10.8,13.2)];
export function createSceneNavigation(){return{
 house:makeNavigation({bounds:[-11.5,11.5,-8.8,18],obstacles:houseObstacles,extra:(x,z)=>z>14.4?Math.abs(x)<1.1:true,floor:()=>.25}),
 cave:makeNavigation({bounds:[-1,19,-71,-36],extra:(wx,wz)=>{const x=wx-9,z=wz+50;return z< -3?Math.abs(x)<.48:z<1?Math.abs(x)<.75:Math.abs(x+z*.1875)<.72},floor:(x,z)=>z>=-68?.65:z<=-69.8?.25:.65-(Math.min(1,(-68-z)/1.8))*.4}),
 overview:makeNavigation({bounds:[-31,31,-26,29],obstacles:[{kind:'circle',x:5,z:12,r:4.6},...[[13,0,1.15],[24,-10,.95],[6,-16,.9],[-13,-12,1],[23,15,1.1],[-17,15,.82]].map(([x,z,s],i)=>rect('cottage-'+i,x-3.2*s,x+3.2*s,z-2.5*s,z+2.5*s)),{kind:'circle',x:-22,z:10,r:.6},{kind:'circle',x:19,z:8,r:.6}],floor:()=>.25}),
 pond:makeNavigation({bounds:[-34,34,-36,35],extra:(x,z)=>((x-2)/8.4)**2+((z-3)/6.05)**2>=1,obstacles:[rect('cottage',-11.5,-6.5,-12,-8.3),rect('left-fence',-14.2,-13.8,2,8),{kind:'circle',x:-11,z:7,r:.65},{kind:'circle',x:14,z:9,r:.6},rect('dock',6.8,11.2,-2.9,.9),rect('field-left',-17.5,-12.5,-5,1),rect('field-back',-5,1,-17.5,-12.5),rect('field-northwest',-18,-12,-19.5,-14.5),...[[ -20,4,.9],[-1,-24,.85],[20,-12,.9],[20,14,.85],[-19,-23,.8],[15,-25,.8]].map(([x,z,k],i)=>rect('extra-house-'+i,x-3.2*k,x+3.2*k,z-2.5*k,z+2.5*k)),{kind:'circle',x:-19,z:15,r:4.3},{kind:'circle',x:11,z:-21,r:3.8},{kind:'circle',x:-25,z:-17,r:3.3},{kind:'circle',x:13,z:28,r:3.3},...[[ -26,20,.8],[-9,27,.85],[6,28,.85],[29,-11,.8]].map(([x,z,k],i)=>rect('new-house-'+i,x-3.2*k,x+3.2*k,z-2.5*k,z+2.5*k)),...[[ -8,17,10,8],[5,16,8,7],[-23,-8,7,9],[17,2,6,6],[5,-30,10,6]].map(([x,z,w,d],i)=>rect('new-field-'+i,x-w/2,x+w/2,z-d/2,z+d/2))],floor:()=>.25})
};}

// Keep one navigation layout while placing it in the shared world.
export function translateNavigation(n,dx,dz){const local=p=>({x:p.x-dx,z:p.z-dz}),world=p=>({x:p.x+dx,z:p.z+dz});return{valid:(x,z)=>n.valid(x-dx,z-dz),floor:(x,z)=>n.floor(x-dx,z-dz),path:(a,b)=>n.path(local(a),local(b)).map(world),clear:(a,b)=>n.clear(local(a),local(b)),nearest:(x,z)=>{const p=n.nearest(x-dx,z-dz);return p?world(p):null},bounds:[n.bounds[0]+dx,n.bounds[1]+dx,n.bounds[2]+dz,n.bounds[3]+dz],obstacles:n.obstacles}}
