export class Soundscape {
 constructor(){this.context=null;this.enabled=false;this.scene='grove';this.steps=0;this.events=0;this.nextEvent=0;this.phase=0;this.profiles={grove:[.28,.06,0,.015],cave:[.07,.025,0,0],overview:[.035,.12,.015,.035],pond:[.10,.16,0,.065],house:[.005,.085,.035,.02],return:[.16,.20,0,.006]};this.names={grove:'溪流 · 林间鸟鸣',cave:'滴水 · 石隙回声',overview:'村落 · 风与鸟鸣',pond:'竹叶 · 水塘虫鸣',house:'庭院 · 微风与鸟鸣',return:'远水 · 山风'};}
 async toggle(){if(!this.context)this.init();await this.context.resume();this.enabled=!this.enabled;this.master.gain.setTargetAtTime(this.enabled?.3:0,this.context.currentTime,.2);this.nextEvent=0;return this.enabled}
 init(){const c=this.context=new AudioContext();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.buffer=c.createBuffer(1,c.sampleRate*4,c.sampleRate);const a=this.buffer.getChannelData(0);let last=0;for(let i=0;i<a.length;i++){last=(last+Math.random()*2-1)*.65;a[i]=last*.5}this.layers=[['lowpass',950],['bandpass',1800],['highpass',2600],['bandpass',5100]].map(([type,freq])=>{const src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=this.buffer;src.loop=true;filter.type=type;filter.frequency.value=freq;filter.Q.value=.5;gain.gain.value=0;src.connect(filter).connect(gain).connect(this.master);src.start();return gain});this.setScene(this.scene)}
 setScene(scene){this.scene=scene;this.nextEvent=0;if(this.context)this.layers.forEach((g,i)=>g.gain.setTargetAtTime(this.profiles[scene][i],this.context.currentTime,.65))}
 tone(freq,end,duration,volume,delay=0){const c=this.context,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(this.master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect()}}
 step(wood=false){if(!this.enabled)return;this.steps++;const c=this.context,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain(),t=c.currentTime;s.buffer=this.buffer;f.type='lowpass';f.frequency.value=wood?650:1300;g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.0001,t+.085);s.connect(f).connect(g).connect(this.master);s.start(t,Math.random()*2,.09);this.tone(wood?140:95,wood?80:55,.075,.045);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect()}}
 update(time,phase,moving,wood){if(!this.enabled){this.phase=phase;return}if(moving&&Math.floor(phase/Math.PI)!==Math.floor(this.phase/Math.PI))this.step(wood);this.phase=phase;if(time<this.nextEvent)return;this.nextEvent=time+3+Math.random()*4;this.events++;if(this.scene==='cave'){this.tone(1250,540,.16,.055);this.tone(1250,540,.2,.018,.22)}else if(this.scene==='house'){if(Math.random()<.5)this.stepCrackle();else{this.tone(2400,3100,.16,.025);this.tone(2900,2300,.13,.020,.24)}}else if(this.scene==='pond'&&Math.random()<.5){this.tone(230,160,.18,.035);this.tone(240,170,.16,.028,.23)}else if(this.scene!=='return'){this.tone(2100,3200,.16,.028);this.tone(2850,2300,.12,.023,.22)}}
 stepCrackle(){this.tone(170,65,.035,.022)}
 state(){return{enabled:this.enabled,scene:this.scene,label:this.names[this.scene],mix:this.profiles[this.scene],steps:this.steps,events:this.events,context:this.context?.state??'not-started'}}
}
