const {chromium}=require('/Users/douer/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));const state=()=>page.evaluate(()=>taoyuan.getState());const ready=async()=>{await page.goto('http://127.0.0.1:4186/?v=24');await page.waitForFunction(()=>window.taoyuan?.getState().ready);};
await ready();await page.evaluate(()=>taoyuan.enterScene('cave'));assert(!(await state()).visitedVillage);await page.getByText('登船 · 划回桃林',{exact:true}).first().click();await page.waitForFunction(()=>taoyuan.getState().sailingOut&&!taoyuan.getState().boarding,null,{timeout:15000});assert((await state()).autoTravel);console.log('PASS boarding without any visit/farewell prerequisite');
await ready();await page.locator('#aerial').click();await page.getByText('靠岸 · 近山溪岸',{exact:true}).click();await page.waitForFunction(()=>taoyuan.getState().groveWalking&&!taoyuan.getState().bankTransfer,null,{timeout:30000});const original=(await state()).landing;await page.getByText('沿岸步行 · 前往山口',{exact:true}).click();await page.waitForFunction(()=>taoyuan.getState().scene==='overview',null,{timeout:60000});assert((await state()).parkedAtBank);assert(!(await state()).mooredBoat.visible);
// Return by keyboard all the way through the tunnel, without any farewell route.
await page.keyboard.down('s');let left=false;const until=Date.now()+45000;
while(Date.now()<until){const s=await state();if(s.scene==='grove'&&s.player[2]>-41.4)break;const desired=9-Math.max(0,s.player[2]+50)*.1875,wantLeft=s.player[0]>desired+.08;if(left!==wantLeft){await page.keyboard[wantLeft?'down':'up']('a');left=wantLeft;}await page.waitForTimeout(100);}
await page.keyboard.up('s');await page.keyboard.up('a');let s=await state();assert.equal(s.scene,'grove');assert(s.groveWalking&&s.parkedAtBank);assert(!s.homeward.length&&!s.farewellDone);assert.deepEqual(s.landing,original);await page.locator('#advance').click();await page.waitForFunction(()=>taoyuan.getState().sailingOut&&!taoyuan.getState().boarding,null,{timeout:30000});s=await state();assert(s.boatVisible&&!s.parkedAtBank&&!s.mooredBoat.visible);assert(s.boatT>=.26&&s.boatT<.5);await page.screenshot({path:'artifacts/bank-departure-v24.png'});assert.deepEqual(errors,[]);console.log('PASS actual bank berth persists through village visit, manual return, shore approach and departure');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
