const {chromium}=require('/Users/douer/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('assert'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>{if(errors.length<2)console.log(e.stack);errors.push(e.message)});p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:4186');await p.waitForFunction(()=>window.taoyuan?.getState().ready);await p.waitForTimeout(1200);const read=()=>p.evaluate(()=>taoyuan.getState());let initial=await read();await p.screenshot({path:'artifacts/grove-v4.png'});await p.waitForTimeout(600);assert((await read()).flowPhase>initial.flowPhase,'flow actually moves');const camera=initial.camera;await p.locator('#advance').click();assert.equal((await read()).scene,'grove','route button must not teleport');await p.waitForFunction(()=>taoyuan.getState().boatT<.28,{timeout:60000});console.log('Approaching landing',await read());assert.notDeepEqual((await read()).camera,camera,'camera follows boat');await p.screenshot({path:'artifacts/approach-v4.png'});await p.waitForFunction(()=>taoyuan.getState().docking,{timeout:45000});await p.screenshot({path:'artifacts/docking-v4.png'});await p.waitForFunction(()=>taoyuan.getState().scene==='cave'&&!taoyuan.getState().transitioning,{timeout:15000});console.log('Docked and entered cave');await p.locator('#advance').click();assert.equal((await read()).scene,'cave','must walk tunnel');await p.waitForFunction(()=>taoyuan.getState().scene==='cave'&&taoyuan.getState().player[2]<-58,{timeout:35000});await p.screenshot({path:'artifacts/tunnel-v4.png'});assert((await read()).walkable,'inside narrow corridor remains walkable');await p.waitForFunction(()=>taoyuan.getState().scene==='overview'&&!taoyuan.getState().transitioning,{timeout:35000});console.log('Cave exit opens village');await p.screenshot({path:'artifacts/village-v4.png'});
await p.locator('#advance').click();assert.equal((await read()).scene,'overview');await p.waitForFunction(()=>taoyuan.getState().scene==='pond'&&!taoyuan.getState().transitioning,{timeout:30000});await p.locator('#advance').click();await p.waitForFunction(()=>taoyuan.getState().scene==='house'&&!taoyuan.getState().transitioning,{timeout:30000});console.log('Walked to pond and house');await p.screenshot({path:'artifacts/house-v4.png'});
// Walk straight at the dining table. Must remain in front of the collider.
await p.keyboard.down('w');const samples=[];for(let i=0;i<18;i++){await p.waitForTimeout(180);samples.push(await read())}await p.keyboard.up('w');assert(samples.every(s=>s.walkable),'never enters furniture');assert(samples.every(s=>s.player[1]>=s.groundHeight-.01),'feet never below floor');assert((await read()).blockedSteps>0,'furniture/wall stops actual key movement');
// Clicking clear floor beyond the table must plan a route around it (same public pointer handler).
await p.locator('[data-scene=house]').click();await p.waitForTimeout(1000);const route=await p.evaluate(async()=>{const n=await import('./navigation.js');return n.createSceneNavigation().house.path({x:0,z:7},{x:0,z:-1.3})});assert(route.length>1,'click navigation can detour around furniture');
await p.locator('.hotspot').filter({hasText:'听村人讲故事'}).click();await p.locator('#finish-talk').click();await p.locator('#advance').click();assert.equal((await read()).scene,'house');await p.waitForFunction(()=>taoyuan.getState().scene==='return'&&!taoyuan.getState().transitioning,{timeout:18000});await p.locator('#advance').click();await p.waitForFunction(()=>document.querySelector('#stay'),{timeout:45000});assert.equal((await read()).collected.length,6);await p.locator('#stay').click();assert.equal((await read()).routeHistory.length,5);console.log('Full six-scene journey passed');
await p.setViewportSize({width:390,height:844});await p.locator('[data-scene=house]').click();await p.waitForTimeout(1000);await p.screenshot({path:'artifacts/mobile-house-v4.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/verification-v4.json',JSON.stringify({passed:true,checks:['current and drifting petals','camera follows boat','visible landing','automatic docking','walk through narrow tunnel','automatic village reveal','walk into pond scene','walk to cottage entrance','NPC and player floor heights','furniture collision under keyboard motion','path around table','dialogue','walk out to return scene','six memories and ending','mobile layout'],errors,samples:samples.map(s=>({player:s.player,walkable:s.walkable,groundHeight:s.groundHeight})),routeHistory:(await read()).routeHistory},null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
