const {chromium}=require('/Users/douer/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');const assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('http://127.0.0.1:4186');await page.waitForFunction(()=>window.taoyuan?.getState().ready);await page.waitForTimeout(1200);const read=()=>page.evaluate(()=>taoyuan.getState());let state=await read();assert.equal(state.scene,'overview');assert(state.triangles>100000);assert(state.meshes<1000);await page.screenshot({path:'artifacts/overview.png'});
const initial=state.camera;await page.locator('#zoom-in').click();assert.notDeepEqual((await read()).camera,initial);await page.locator('#zoom-out').click();await page.locator('#reset-view').click();await page.waitForTimeout(1000);const before=(await read()).camera;await page.mouse.move(880,620);await page.mouse.down();await page.mouse.move(1020,610,{steps:15});await page.mouse.up();await page.waitForTimeout(400);assert.notDeepEqual((await read()).camera,before);await page.locator('#reset-view').click();await page.waitForTimeout(1000);
await page.locator('.hotspot').filter({hasText:'桃花渡'}).click();await page.waitForTimeout(1100);assert.equal((await read()).scene,'grove');const pos=(await read()).player;await page.keyboard.down('d');await page.waitForTimeout(400);await page.keyboard.up('d');assert.notDeepEqual((await read()).player,pos);await page.screenshot({path:'artifacts/grove.png'});await page.locator('.collect').click();assert.equal((await read()).collected.length,1);await page.keyboard.press('Escape');assert.equal((await read()).scene,'overview');
for(const id of ['cave','pond','house']){await page.locator(`[data-scene=${id}]`).click();await page.waitForTimeout(1100);assert.equal((await read()).scene,id);await page.screenshot({path:`artifacts/${id}.png`});await page.locator('.collect').click()}
await page.waitForTimeout(1200);assert(await page.locator('#stay').isVisible());assert.equal((await read()).collected.length,4);await page.locator('#stay').click();await page.locator('#journal').click();assert.equal(await page.locator('.entry:not(.locked)').count(),4);await page.locator('.close').click();await page.reload();await page.waitForFunction(()=>window.taoyuan?.getState().ready);assert.equal((await read()).collected.length,4);await page.locator('#sound').click();assert.equal((await read()).audioOn,true);await page.locator('#sound').click();assert.equal((await read()).audioOn,false);
const download=page.waitForEvent('download');await page.locator('#capture').click();await(await download).saveAs('artifacts/景色.png');await page.locator('#help').click();assert(await page.locator('dialog').isVisible());await page.keyboard.press('Escape');assert(!await page.locator('dialog').isVisible());
await page.setViewportSize({width:390,height:844});await page.locator('#reset-view').click();await page.waitForTimeout(1100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/mobile.png'});await page.locator('[data-scene=house]').click();await page.waitForTimeout(1100);assert.equal((await read()).scene,'house');await page.screenshot({path:'artifacts/mobile-house.png'});await page.locator('#back').click();assert.equal((await read()).scene,'overview');
await page.locator('#journal').click();await page.locator('#clear-progress').click();assert.equal((await read()).collected.length,0);await page.reload();await page.waitForFunction(()=>window.taoyuan?.getState().ready);assert.equal((await read()).collected.length,0);assert.deepEqual(errors,[]);const result={passed:true,checks:['3D world renders','static batching below 1000 draw calls','zoom in/out','orbit drag','reset camera','3D scene label navigation','WASD movement','four distinct scenes','four collectible memories','ending dialog','journal content','progress persists on reload','audio toggle','photo download','help and Escape','mobile 390px no overflow','mobile scene navigation','progress reset persists'],errors};fs.writeFileSync('artifacts/verification.json',JSON.stringify(result,null,2));console.log(result);await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
